server:
  port: 8089

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: integration-service
          uri: http://localhost:8081
          predicates:
            - Path=/integration/**
