spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=e-commerce-local
    username: postgres
    password: postgres
    hikari:
      minimum-idle: 1
      maximum-pool-size: 10
      idle-timeout: 300000
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    repositories:
      bootstrap-mode: deferred